title: Bosch/Buderus Wärmepumpen
subtitle: CS 5800/6800i & WLW176/186
locale: de-DE
url: "https://bosch-buderus-wp.github.io"
baseurl: "/"
repository: "bosch-buderus-wp/bosch-buderus-wp"
search: true
search_full_content: true

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      sidebar:
        nav: "docs"
